
(async()=>{const root=document.getElementById('app'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let D;try{D=await fetch('intercambio.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()})}catch(e){root.innerHTML='<div class="intro">Não foi possível carregar as informações.</div>';return}
const lis=a=>`<ul>${a.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
root.innerHTML=`<section class="hero"><div class="eyebrow">UFPR · CURSO DE BIOMEDICINA</div><h1>${esc(D.title)}</h1><p>${esc(D.subtitle)}</p></section>
<div class="intro">${esc(D.intro)}</div>
<div class="quick">${D.quick.map(x=>`<a href="${esc(x.target)}">${esc(x.label)}</a>`).join('')}</div>
<section class="section"><h2>Quero fazer mobilidade. Por onde começo?</h2><div class="flow">${D.flow.map(x=>`<article class="step"><div class="num">${esc(x.step)}</div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div></section>
<section class="section"><div class="two"><article class="card" id="internacional"><h3>${esc(D.international.title)}</h3><p>${esc(D.international.text)}</p>${D.international.links.map(l=>`<a class="btn" href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.label)}</a> `).join('')}</article><article class="card" id="nacional"><h3>${esc(D.national.title)}</h3><p>${esc(D.national.text)}</p>${D.national.links.map(l=>`<a class="btn" href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.label)}</a>`).join('')}</article></div></section>
<section class="section"><h2>${esc(D.registration.title)}</h2><div class="card"><p>${esc(D.registration.text)}</p>${lis(D.registration.documents)}<a class="btn" href="${esc(D.registration.url)}" target="_blank" rel="noopener">Procedimento oficial do ERI</a><div class="notice"><b>Ao chegar ao destino:</b> ${D.registration.arrival.map(esc).join(' ou ')}.</div></div></section>
<section class="section" id="estagio"><h2>${esc(D.internship.title)}</h2><div class="card"><p>${esc(D.internship.text)}</p><div class="checks">${D.internship.checklist.map(x=>`<div class="check">✓ ${esc(x)}</div>`).join('')}</div><div class="notice">${esc(D.internship.note)}</div><a class="btn" href="${esc(D.internship.estagios_url)}" target="_blank" rel="noopener">Estágios — Biomedicina</a></div></section>
<section class="section" id="retorno"><h2>${esc(D.return.title)}</h2><div class="two"><article class="card"><p>${esc(D.return.text)}</p>${lis(D.return.steps)}<a class="btn" href="${esc(D.return.forms_url)}" target="_blank" rel="noopener">Formulários da Biomedicina</a></article><article class="card"><h3>${esc(D.planning.title)}</h3><p>${esc(D.planning.text)}</p></article></div></section>
<section class="section"><h2>${esc(D.calls.title)}</h2><div class="calls">${D.calls.items.map(c=>`<article class="call"><span class="status">${esc(c.status)}</span><h3>${esc(c.program)} — ${esc(c.departure)}</h3><div class="meta"><b>Inscrições:</b> ${esc(c.application)}</div><a class="btn" href="${esc(c.url)}" target="_blank" rel="noopener">Consultar chamada</a></article>`).join('')}</div><div class="notice">${esc(D.calls.note)} <a href="${esc(D.calls.official_url)}" target="_blank" rel="noopener">Consultar chamadas oficiais</a>.</div></section>
<section class="section"><h2>Acessos importantes</h2><div class="links">${D.links.map(l=>`<article class="linkcard"><a href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.label)}</a></article>`).join('')}</div></section>
<section class="section"><h2>Contato</h2><div class="panel contact">Coordenação: <a href="mailto:${esc(D.contact.course_email)}">${esc(D.contact.course_email)}</a> · Mobilidade ERI: <a href="mailto:${esc(D.contact.eri_mobility_email)}">${esc(D.contact.eri_mobility_email)}</a></div></section>`;})();
